# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f56b3e0aa5f08abad60b7ed46372f3c778308b4db582d7c4650f3388a0361d4a7a618a132928391448a5e59764bc206556996973e96d7f02e71b8bd09333408a

test:
  secret_key_base: 0fdaa2eedaf7e7ab1e43806b8ecd9230fa6671ff211cebe292c9d2f991348ac1c2b4b07a28cade95ea7f7c94ed3c3254047c43a6fe2fc98d1fe532e2076399c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
